language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:  
  email:
    recipients:
      - open.hardware.libre@gmail.com
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sip-informatica -Dsonar.login=$SONAR -Dsonar.coverage.exclusions="**/api/*, **/configurations/*"
deploy:
  provider: heroku
  api_key: $HEROKU  
  app: 
    develop: sip-property-management
