POST http://localhost:8080/api/auth/signup HTTP/1.1
content-Type: application/json

{
    "username": "AdminManager",
    "email": "adminmanager@sip.es",
    "password": "passAdminManager",
    "phone": "600000000",
    "role": ["admin","manager"]
}
###
POST http://localhost:8080/api/auth/signup HTTP/1.1
content-Type: application/json

{
    "username": "manager",
    "email": "manager@sip.es",
    "password": "passManager",
    "phone": "660000000",
    "role": ["manager"]
}
###
POST http://localhost:8080/api/auth/signup HTTP/1.1
content-Type: application/json

{
    "username": "admin",
    "email": "admin@sip.es",
    "password": "passAdmin",
    "phone": "666000000",
    "role": ["admin"]
}
###
GET http://localhost:8080/api/test/all HTTP/1.1
###
GET http://localhost:8080/api/test/exception/handleall HTTP/1.1
###
POST http://localhost:8080/api/auth/signin HTTP/1.1
content-Type: application/json

{
    "username": "admin",   
    "password": "passAdmin"    
}
###
GET http://localhost:8080/api/test/admin HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNjMzNDUzNjkzLCJleHAiOjE2MzM1NDAwOTN9.B6QzxMWjYP-fotkdbYQuk2AtoDVEE9-bwfTa5E5k3S_LVLjI-MO02LkjctQaMwHxxFMUVtzOzsJahZPg5MNkaA
###
POST http://localhost:8080/api/auth/signin HTTP/1.1
content-Type: application/json

{
    "username": "manager",   
    "password": "passManager"    
}
###
GET http://localhost:8080/api/test/manager HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsImlhdCI6MTY0MzExNjM3MCwiZXhwIjoxNjQzMjAyNzcwfQ.UurBFHnqxD7Y2zmnnKOd0BuU-mwGy3eRxUXQM8ViqSar_twKDaGW4fKKSLgVQ0_w-1ChkLIJq1Gbso9n7JeLhA
###
POST http://localhost:8080/api/auth/signin HTTP/1.1
content-Type: application/json

{
    "username": "AdminManager",   
    "password": "passAdminManager"    
}
###
GET http://localhost:8080/api/test/adminmanager HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZG1pbk1hbmFnZXIiLCJyb2xlIjoiUk9MRV9BRE1JTixST0xFX01BTkFHRVIiLCJpYXQiOjE2Mjc4NDc5OTIsImV4cCI6MTYyNzkzNDM5Mn0.G8vMWPokTU8qI642fcVM7YO-Rpm2WRcTyyQKX7Jve78eVUWTo7f3fh3yfCBc1UiOceZBw4QmFU_7arlGaHM-Bg

###
GET http://localhost:8080/api/admin/users-admin HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNjMzNDUzNjkzLCJleHAiOjE2MzM1NDAwOTN9.B6QzxMWjYP-fotkdbYQuk2AtoDVEE9-bwfTa5E5k3S_LVLjI-MO02LkjctQaMwHxxFMUVtzOzsJahZPg5MNkaA
###
DELETE  http://localhost:8080/api/admin/users-admin/email/v@v.es HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZG1pbk1hbmFnZXIiLCJyb2xlIjoiUk9MRV9BRE1JTixST0xFX01BTkFHRVIiLCJpYXQiOjE2Mjc4NDc5OTIsImV4cCI6MTYyNzkzNDM5Mn0.G8vMWPokTU8qI642fcVM7YO-Rpm2WRcTyyQKX7Jve78eVUWTo7f3fh3yfCBc1UiOceZBw4QmFU_7arlGaHM-Bg

###
###
GET http://localhost:8080/api/test/operator HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBZG1pbk1hbmFnZXIiLCJyb2xlIjoiUk9MRV9NQU5BR0VSLFJPTEVfQURNSU4iLCJpYXQiOjE2MTIzNTE1NDAsImV4cCI6MTYxMjQzNzk0MH0.chr85HoKEFCEBQKBv9j-LxvBDA4vyyuIKAXluUwlz-R4QIRZFx0m4cMVGFtf6hMiL1ccyp1ZpCLYI-FufYr-Ew
###
GET http://localhost:8080/api/test/authenticated HTTP/1.1
content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsImlhdCI6MTY0MzExNjM3MCwiZXhwIjoxNjQzMjAyNzcwfQ.UurBFHnqxD7Y2zmnnKOd0BuU-mwGy3eRxUXQM8ViqSar_twKDaGW4fKKSLgVQ0_w-1ChkLIJq1Gbso9n7JeLhA

###
POST http://localhost:8080/api/admin/users-admin HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyIiwicm9sZSI6IlJPTEVfTUFOQUdFUiIsImlhdCI6MTY0MzExNjM3MCwiZXhwIjoxNjQzMjAyNzcwfQ.UurBFHnqxD7Y2zmnnKOd0BuU-mwGy3eRxUXQM8ViqSar_twKDaGW4fKKSLgVQ0_w-1ChkLIJq1Gbso9n7JeLhA

 {
    "phone": "33rr33r33",
    "email": "ailn@sip.es",
    "dni": "rrrrrrytyttry",
    "password": "secttet",
    "isEnabled": true,
    "roles": [
      "ROLE_MANAGER",
      "ROLE_ADMIN"
    ],
    "username": "admingo",
    "isAccountNonExpired": true,
    "isAccountNonLocked": true,
    "isCredentialsNonExpired": true
  }

###
POST http://localhost:8080/api/auth/register HTTP/1.1
content-Type: application/json

{
    "username": "UserTest",   
    "password": "1passAdminManager", 
    "phone": "194578459",
    "email": "@gmail.com",
    "dni": "68371422N"     
}
###

